- Infraestructura:
    - Portainer:
        # href: https://IP-DEL-SERVIDOR:9443
        icon: portainer.png
        server: local
        container: portainer
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        container: npm
        server: local
    - Pi-hole:
        icon: pi-hole.png
        container: pihole
        server: local
- Monitorización:
    - Uptime Kuma:
        icon: uptime-kuma.png
        container: uptime-kuma
        server: local
    - Netdata:
        icon: netdata.png
- Apps:
    - Jellyfin:
        icon: jellyfin.png
        container: jellyfin
        server: local
    - Immich:
        href: http://192.168.1.26:2283
        icon: immich.png
        container: immich_server
        server: local
    - Home Assistant:
        href: http://192.168.1.26:8123
        icon: home-assistant.png
        container: homeassistant
        server: local
    - Ollama:
        icon: ollama.png
        container: ollama
        server: local
    - Vaultwarden:
        icon: vaultwarden.png
        container: vaultwarden
        server: local
